### ISSUE TITLE
Broken Advancement

### ISSUE THREAD

**Issue by Fourmisain** [Jamalam360/ReapingFabric#1]
Picking up any item in 1.17 unlocks the "Why would you do that?" advancement.

I've heard that item conditions now have to use `"items"` instead of `"item"`, so this line
https://github.com/Jamalam360/ReapingFabric/blob/c956d5664a7acfd5bcc06b8f3e845f25fd7cb89b/src/main/resources/data/reapingmod/advancements/obtain_netherite_reaper.json#L28

Should be `"items": ["reapingmod:netherite_reaping_tool"]`, haven't tested this though.

**Comment by Jamalam360** [comment]
Thanks, I'll fix this in the latest release

**Comment by Jamalam360** [comment]
Fixed in d4ba5ca563744a418da291a52ad7efa82f98029e thanks
