### ISSUE TITLE
Sweep Attacks and XP Drops (from CF comments)

### ISSUE THREAD

**Issue by Jamalam360** [Jamalam360/ReapingFabric#2]
Really fun idea!

 

I have a few suggestions:

- give the reapers an AOE attack (they are scythes afterall!) similar to swords, ideally not dealing any damage to animals, only reaping them

- make the animals drop XP when reaped "manually" by a player

 

The latter is the main reason why I feel I won't end up using this mod (in this form), since I usually cycle between breeding and killing to not only get the "products" but a respectable amount of XP too - a "space efficient" chicken farm with a few hundred chickens is just too good for that.

Balancing the dropped XP might be a bit hard. Animals drop 1-3 XP when killed and breeding gives 1-7 XP.

 

The former will effectively increase the tool durability by a factor since you can reap multiple animals in 1 hit, so durability would probably need to be adjusted.

 

I'm also a bit torn on the idea of automating the farming via dispensers, since that does sound pretty OP, especially since there's now cheap (farmable) iron and gold reapers.

Though you don't have to use it, maybe some config switches wouldn't be a bad idea?

**Comment by Fourmisain** [comment]
I took a look at the recent changes and since you closed this issue I was wondering if you'll implement the

> AOE attack (...) ideally not dealing any damage to animals, only reaping them

and

> animals drop XP when reaped

parts as well?

(If not that's fine too!)

**Comment by Jamalam360** [comment]
The animals being reaped on the AOE attack is something I was going to do but it required some complex mixins because Mojang hard coded all of the sweep attack stuff. I now know how I'm going to do it though and I'll add it when I fix that mixin crash

The XP dropping I just forgot to do lol, I'll add it then as well

**Comment by Jamalam360** [comment]
Reopened so I remember
